### ISSUE TITLE
update not working with 1.9.49

### ISSUE THREAD

**Issue by epspot** [GoogleCloudPlatform/appengine-maven-plugin#80] opened 2017-02-03 23:02 UTC
After updating SDK and maven-plugin to 1.9.49 I'm no longer able to update my app via mvn appengine:update.
Error I get is:

`org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.google.appengine:appengine-maven-plugin:1.9.49:update (default-cli) on project backend-server-ear: No <application> defined in appengine-web.xml, nor <appId> <configuration> defined in the pom.xml.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
`

My app is an EAR containing 4 modules (services).

Rollback to 1.9.48 fixes the problem for me short term and app deploys as usual.

**Comment by patrickconant** [comment] 2017-02-17 00:29
I experienced the same problem. Rolling back to 1.9.48 fixed the problem for me too.

**Comment by ludoch** [comment] 2017-02-17 01:32
Looking.

**Comment by ludoch** [comment] 2017-02-19 01:56
Will be in 1.9.50 soon.

**Closed by ludoch** 2017-02-19 01:56 UTC

**Comment by patrickconant** [comment] 2017-02-19 03:32
Thanks, Ludoch.

**Comment by ZiglioNZ** [comment] 2017-07-09 22:48
I'm getting the same error with 1.9.54, not sure why because last week I did manage to deploy a new version. "appId" is certainly defined both in appengine-web.xml and pom.xml.

`[ERROR] Failed to execute goal com.google.appengine:appengine-maven-plugin:1.9.54:update (default-cli) on project iridiu
m: No <application> defined in appengine-web.xml, nor <appId> <configuration> defined in the pom.xml. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.google.appengine:appengine-maven-plug
in:1.9.54:update (default-cli) on project iridium: No <application> defined in appengine-web.xml, nor <appId> <configura
tion> defined in the pom.xml.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.
java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: No <application> defined in appengine-web.xml, nor <appId> <c
onfiguration> defined in the pom.xml.
        at com.google.appengine.appcfg.AbstractAppCfgMojo.collectParameters(AbstractAppCfgMojo.java:354)
        at com.google.appengine.appcfg.AbstractAppCfgMojo.executeAppCfgCommand(AbstractAppCfgMojo.java:257)
        at com.google.appengine.appcfg.Update.execute(Update.java:32)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`
